baseURL = "/"
languageCode = "en-us"
title = "Handell Désulmé"
paginate = 10
theme = "hugo-coder"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Privacy"
  url = "/privacy/"
  weight = 2
[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

[params]
  author = "Handell Désulmé"
  info = "Fullstack Software Engineer"
  description = "Explore my projects, skills, and thoughts on software engineering through the lens of cellular automata."
  about = "I'm a Haitian-American from Philadelphia, PA. And I'm a firm believer in the power of STEM (& God) to save lives and transform communities. My main goal, outside of breaking back into the tech industry as a software engineer and upskilling as much as I can, is to inspire other kids who look like me, and who may have lacked hope as I did as a child, to overcome obstacles and turn their dreams into plans."
  twitter_url = "https://twitter.com/HandellDesulme"
  github_url = "https://github.com/hjdesulme"
  linkedin_url = "https://linkedin.com/in/hjdesulme"
  customCSS = ["/css/custom.css"]
  publishDir = "public"
